// Generated by CoffeeScript 1.10.0

/**
 * Created by gitbong on 8/13/16.
 * github:gitbong
 */

(function() {
  var Signal;

  Signal = (function() {
    Signal.prototype.map = [];

    function Signal() {
      this.map = [];
    }

    Signal.prototype.add = function(fn, scope) {
      if (scope == null) {
        scope = window;
      }
      return this.map.push({
        fn: fn,
        scope: scope,
        addOnce: false,
        destroy: false
      });
    };

    Signal.prototype.addOnce = function(fn, scope) {
      if (scope == null) {
        scope = window;
      }
      return this.map.push({
        fn: fn,
        scope: scope,
        addOnce: true,
        destroy: false
      });
    };

    Signal.prototype.remove = function() {};

    Signal.prototype.dispatch = function() {
      var addOnce, destroy, fn, i, len, obj, ref, scope;
      ref = this.map;
      for (i = 0, len = ref.length; i < len; i++) {
        obj = ref[i];
        fn = obj.fn;
        scope = obj.scope;
        addOnce = obj.addOnce;
        destroy = obj.destroy;
        if (!destroy) {
          fn.apply(scope, arguments);
        }
        if (addOnce) {
          obj.destroy = true;
        }
      }
    };

    return Signal;

  })();

  window.gbSignal = Signal;

}).call(this);

//# sourceMappingURL=gbSignal.js.map
